x-common-vars: &ros2-vars
  stdin_open: true
  tty: true
  privileged: true
  stop_grace_period: 1s
  restart: no
  network_mode: host
  working_dir: /home/user/localization-ws
  environment:
    # - DISPLAY=${DISPLAY}
    # Set ros2 environment variables.
    # References:
    # - https://docs.ros.org/en/humble/Concepts/Intermediate/About-Domain-ID.html
    # - https://docs.ros.org/en/humble/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html
    # - ROS_LOCALHOST_ONLY=1
    - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
    - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    - ROS_WS=/home/user/localization-ws
  volumes:
    # Mount local timezone into container. ( Readonly )
    # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
    - /etc/timezone:/etc/timezone:ro
    - /etc/localtime:/etc/localtime:ro
    # Mount X11 server
    - /tmp/.X11-unix:/tmp/.X11-unix
    # Direct Rendering Infrastructure
    # - /dev/dri:/dev/dri
    # Mount sound card to prevent Gazebo warning.
    # - /dev/snd:/dev/snd
    - /dev:/dev
    # Mount workspace
    - ../../localization-devel-ws:/home/user/localization-ws/src/localization-devel-ws

services:

  localization-main:
    profiles: ['localization_main']
    image: jossiewang/eurobot2025-localization:devel
    container_name: localization-main
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        ros2 launch ${ROS2_LAUNCH_FILE}"

  localization-FixObstacleCPU:
    profiles: ['localization_FixObstacleCPU']
    image: jossiewang/eurobot2025-localization2:FixObstacleCPU
    container_name: localization-FixObstacleCPU
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        ros2 launch ${ROS2_LAUNCH_FILE}"

  localization-DistorsionCorrection:
    profiles: ['localization_DistorsionCorrection']
    image: jossiewang/eurobot2025-localization2:DistorsionCorrection
    container_name: localization-DistorsionCorrection
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        ros2 launch ${ROS2_LAUNCH_FILE}"
  localization-OdomTF:
    profiles: ['localization_OdomTF']
    image: jossiewang/eurobot2025-localization2:OdomTF
    container_name: localization-OdomTF
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        ros2 launch ${ROS2_LAUNCH_FILE}"

  localization-devel:
    profiles: ['localization_devel']
    # image: jossiewang/eurobot2025-localization:rotop
    build: 
      context: .
      dockerfile: Dockerfile
      target: devel-ws
      args:
        USERNAME: user
        PACKAGE_SELECT: ${PACKAGE_SELECT}
        BRANCH_SELECT: ${BRANCH_SELECT}
    container_name: localization_devel
    <<: 
      - *ros2-vars
    command: /bin/bash
  
  localization-build-run:
    profiles: ['build_and_run']
    image: jossiewang/eurobot2025-localization2:testbot-release
    container_name: localization_build_run
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        cd /home/user/localization-ws &&
        colcon build --packages-select ${PACKAGE_SELECT} --cmake-args -DCMAKE_BUILD_TYPE=Release &&
        source /home/user/localization-ws/install/setup.bash &&
        ros2 launch ${ROS2_LAUNCH_FILE}"

  localization-record:
    profiles: ['record']
    image: jossiewang/eurobot2025-localization:local-ros2-wSensors
    container_name: localization_record
    <<: 
      - *ros2-vars
    command: /bin/bash -c "
        source /opt/ros/humble/setup.bash && 
        source /home/user/localization-ws/install/setup.bash &&
        ros2 bag record -o ${BAG_NAME} \
           /local_filter \
          /lidar_pose \
          /final_pose \
          /tf \
          /tf_static \
          /odom2map \
          /rival/final_pose \
          /raw_obstacles \
          /raw_obstacles_visualization_pcl \
          /candidates"

  localization-bash:
    profiles: ['localization_bash']
    image: jossiewang/eurobot2025-localization:local-ros2-wSensors
    container_name: localization-bash
    <<: 
      - *ros2-vars
    command: /bin/bash

  ros-core:
    profiles: ['communication']
    image: osrf/ros:noetic-desktop-full
    container_name: ros-core
    command: "rosmaster --core"
    network_mode: host
    stop_grace_period: 1s
    healthcheck:
      # The healthcheck is required for ros1-bridge to wait until roscore is ready.
      test: /ros_entrypoint.sh bash -c "rostopic list || exit 1"
      interval: 3s
      timeout: 10s
      retries: 5

  ros1-bridge:
    profiles: ['communication']
    build:
      context: .
      target: release
    image: pomelo925/ttennis-humble:communication
    container_name: ros2-ros1-bridge-ws
    stop_grace_period: 1s
    depends_on:
      ros-core:
        # The healthcheck is required for ros1-bridge to wait until roscore is ready.
        condition: service_healthy
    command: ./start-bridge.sh
    stdin_open: true
    tty: true
    network_mode: host
    working_dir: /
    volumes:
      # Mount local timezone into container. ( Readonly )
      # Reference: https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # Direct Rendering Infrastructure
      - /dev/dri:/dev/dri
      # Shared Memory
      - /dev/shm:/dev/shm
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      # - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp=value

  ros1:
    profiles: ['communication']
    image: jossiewang/eurobot2025-localization:rosserial-chassis
    container_name: ros1
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /dev:/dev
    stop_grace_period: 1s
    depends_on:
      ros-core:
        condition: service_healthy
    command: /bin/bash -c "
            source /opt/ros/noetic/setup.bash && 
            source ~/ws/devel/setup.bash &&
            roslaunch odometry odometry_comm.launch"